# -*- coding: utf-8 -*-
"""CC_Supercentro - Simulación - entrega final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12V2i3AK2lba04CGav_Ij2na2olE4aGqE
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats

np.random.seed(42)

# 1. PARAMETRIZACIÓN DEL MODELO (CALIBRACIÓN)

PROBS = [0.25, 0.20, 0.275, 0.275]  # Rápido, Normal, Lento, Muy Lento
TIEMPOS_SERVICIO = [1.0, 3.0, 4.0, 6.0]
TIEMPOS_LLEGADA = [3.0, 3.0, 5.0, 7.0]
NOMBRES_TIPOS = ['Rápido', 'Normal', 'Lento', 'Muy Lento']

# Cálculo de parámetros globales compuestos (Análisis Teórico)
t_servicio_ponderado = sum(p * t for p, t in zip(PROBS, TIEMPOS_SERVICIO))
t_llegada_ponderado = sum(p * t for p, t in zip(PROBS, TIEMPOS_LLEGADA))

lambda_global = 1.0 / t_llegada_ponderado
mu_global = 1.0 / t_servicio_ponderado
num_cajeros = 3
lambda_por_cajero = lambda_global / num_cajeros

print("="*50)
print("     CALIBRACIÓN INICIAL DEL MODELO GLOBAL")
print("="*50)
print(f"Tiempo de Servicio Ponderado Teórico: {t_servicio_ponderado:.2f} min")
print(f"Tiempo entre Llegadas Ponderado Teórico: {t_llegada_ponderado:.2f} min")
print(f"Factor de Utilización Real por Cajero (Rho): {lambda_por_cajero/mu_global:.4f} ({lambda_por_cajero/mu_global*100:.1f}%)")
print("="*50 + "\n")

# 2. MOTOR DE SIMULACIÓN DE EVENTOS DISCRETOS

def simular_cajero_parqueadero(num_clientes=2500):
    tiempo_actual = 0.0
    tiempos_llegada = []
    tiempos_servicio_asignados = []
    tipos_usuario = []

    # Generación de arribos exponenciales y asignación estocástica de perfiles
    for _ in range(num_clientes):
        tiempo_actual += np.random.exponential(1.0 / lambda_por_cajero)
        tiempos_llegada.append(tiempo_actual)

        # Selección del tipo de cliente basado en probabilidades empíricas
        tipo = np.random.choice([0, 1, 2, 3], p=PROBS)
        tipos_usuario.append(tipo)

        # Asignación de tiempo de servicio con distribución exponencial según tipo
        tiempos_servicio_asignados.append(np.random.exponential(TIEMPOS_SERVICIO[tipo]))

    # Vectores de salida de la fila (Verificación lógica)
    tiempo_inicio_servicio = np.zeros(num_clientes)
    tiempo_fin_servicio = np.zeros(num_clientes)
    tiempos_espera_cola = np.zeros(num_clientes)
    tiempos_en_sistema = np.zeros(num_clientes)

    for i in range(num_clientes):
        if i == 0:
            tiempo_inicio_servicio[i] = tiempos_llegada[i]
        else:
            # Regla de oro de verificación: No puede iniciar antes de llegar ni antes de que se libere el anterior
            tiempo_inicio_servicio[i] = max(tiempos_llegada[i], tiempo_fin_servicio[i-1])

        tiempos_espera_cola[i] = tiempo_inicio_servicio[i] - tiempos_llegada[i]
        tiempo_fin_servicio[i] = tiempo_inicio_servicio[i] + tiempos_servicio_asignados[i]
        tiempos_en_sistema[i] = tiempo_fin_servicio[i] - tiempos_llegada[i]

    return tiempos_espera_cola, tiempos_en_sistema, tiempos_servicio_asignados, tipos_usuario

# Simulación independiente de los 3 cajeros del Supercentro
cajeros_resultados = {}
for c in range(1, num_cajeros + 1):
    wq, w, s, t = simular_cajero_parqueadero(num_clientes=2500)
    cajeros_resultados[f'Cajero_{c}'] = {'Wq': wq, 'W': w, 'Servicio': s, 'Tipos': t}

# 3. ELIMINACIÓN DEL ESTADO TRANSITORIO

punto_corte = 400  # Período de calentamiento (Warm-up) determinado gráficamente

def calcular_promedio_movil(datos, ventana=150):
    return np.convolve(datos, np.ones(ventana)/ventana, mode='valid')

datos_crudos_w = cajeros_resultados['Cajero_1']['W']
datos_suavizados_w = calcular_promedio_movil(datos_crudos_w, ventana=150)

# --- GRÁFICA: ANTES Y DESPUÉS DEL ESTADO TRANSITORIO ---
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# Lado Izquierdo: Identificación del Transitorio
ax1.plot(datos_crudos_w, color='gray', alpha=0.3, label='Tiempo W Individual')
ax1.plot(range(149, len(datos_crudos_w)), datos_suavizados_w, color='blue', linewidth=2, label='Promedio Móvil (Ventana 150)')
ax1.axvline(x=punto_corte, color='red', linestyle='--', linewidth=2, label=f'Corte de Calentamiento ({punto_corte} cl)')
ax1.set_title('Antes: Identificación del Período Transitorio')
ax1.set_xlabel('Índice de Cliente')
ax1.set_ylabel('Tiempo en Sistema (Minutos)')
ax1.legend()
ax1.grid(True, alpha=0.3)

# Lado Derecho: Estado Estable Puro (Después)
datos_estables_w = datos_crudos_w[punto_corte:]
ax2.plot(range(punto_corte, len(datos_crudos_w)), datos_estables_w, color='green', alpha=0.4, label='Datos en Estado Estable')
ax2.axhline(y=np.mean(datos_estables_w), color='darkgreen', linestyle='-', linewidth=2.5, label=f'Media Estable: {np.mean(datos_estables_w):.2f} min')
ax2.set_title('Después: Sistema purgado en Estado Estable')
ax2.set_xlabel('Índice de Cliente')
ax2.set_ylabel('Tiempo en Sistema (Minutos)')
ax2.legend()
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# 4. EXTRACCIÓN DE RESULTADOS (INFORME FINAL)

print("\n" + "="*50)
print("       RESULTADO FINAL")
print("="*50)

# PROCESAMIENTO PUNTO 1: Tiempos de Atención por Cajero
print("\n[RESPUESTA PUNTO 1] Estadísticas de Atención por Máquina (Fase Estable):")
medias_atencion = {}
for c, datos in cajeros_resultados.items():
    servicios_puros = datos['Servicio'][punto_corte:]
    media = np.mean(servicios_puros)
    medias_atencion[c] = media
    desv = np.std(servicios_puros, ddof=1)
    minimo = np.min(servicios_puros)
    maximo = np.max(servicios_puros)

    # Intervalo de confianza del 95% para la media
    ic_inf, ic_sup = stats.t.interval(0.95, len(servicios_puros)-1, loc=media, scale=stats.sem(servicios_puros))

    print(f"  * {c}:")
    print(f"   - Tiempo Promedio de Atención: {media:.3f} minutos")
    print(f"   - Desviación Estándar: {desv:.3f} min | Rango: [{minimo:.2f} - {maximo:.2f}] min")
    print(f"   - Intervalo de Confianza 95%: [{ic_inf:.3f} , {ic_sup:.3f}]")

# ADICIONAL: Cajero con menor y mayor tiempo promedio de atención
cajero_min = min(medias_atencion, key=medias_atencion.get)
cajero_max = max(medias_atencion, key=medias_atencion.get)
print("\n[ADICIONAL] Comparativa de Cajeros:")
print(f"   - Cajero con MENOR tiempo promedio de atención: {cajero_min} ({medias_atencion[cajero_min]:.3f} minutos)")
print(f"   - Cajero con MAYOR tiempo promedio de atención: {cajero_max} ({medias_atencion[cajero_max]:.3f} minutos)")

# PROCESAMIENTO PUNTO 2: Distribución de Usuarios
print("\n[RESPUESTA PUNTO 2] Distribución de Usuarios en la Totalidad de Cajeros:")
total_clientes_analizados = 0
conteos_usuarios = np.zeros(4)

for c, datos in cajeros_resultados.items():
    tipos_puros = datos['Tipos'][punto_corte:]
    total_clientes_analizados += len(tipos_puros)
    for t in tipos_puros:
        conteos_usuarios[t] += 1

for i in range(4):
    porcentaje_obtenido = (conteos_usuarios[i] / total_clientes_analizados) * 100
    print(f"   - Tipo [{NOMBRES_TIPOS[i].upper()}]: Esperado {PROBS[i]*100:.1f}% | Simulado Real: {porcentaje_obtenido:.2f}% ({int(conteos_usuarios[i])} clientes)")

# ADICIONAL: Promedio de usuarios de cada tipo en la totalidad de cajeros
promedio_usuarios_por_tipo = conteos_usuarios / num_cajeros
print("\n[ADICIONAL] Promedio de usuarios de cada tipo por cajero (fase estable):")
for i in range(4):
    print(f"   - Tipo [{NOMBRES_TIPOS[i]}]: promedio de {promedio_usuarios_por_tipo[i]:.1f} usuarios por cajero")

# 5. GRÁFICA DE VALIDACIÓN CON LA TEORÍA M/M/1

# Gráfica adicional para sustentar el punto 4 (Proceso de Validación)
plt.figure(figsize=(10, 5))
cajeros_nombres = list(cajeros_resultados.keys())
medias_simuladas_w = [np.mean(cajeros_resultados[c]['W'][punto_corte:]) for c in cajeros_nombres]

# El tiempo total promedio analítico teórico en el sistema M/M/1 es W = 1 / (mu - lambda)
W_teorico_mm1 = 1.0 / (mu_global - lambda_por_cajero)

plt.bar(cajeros_nombres, medias_simuladas_w, color='lightblue', edgecolor='blue', alpha=0.7, label='Simulación Empírica (Fase Estable)')
plt.axhline(y=W_teorico_mm1, color='red', linestyle='--', linewidth=2, label=f'Modelo Teórico M/M/1 Analítico ({W_teorico_mm1:.2f} min)')
plt.title('Validación del Modelo: Tiempos del Sistema vs Ecuaciones M/M/1')
plt.xlabel('Cajeros Evaluados')
plt.ylabel('Tiempo Promedio Total en el Sistema (W)')
plt.ylim(0, max(medias_simuladas_w) + 2)
plt.legend()
plt.grid(True, alpha=0.2)
plt.show()

# 6. ANÁLISIS ESTRATÉGICO Y PROCESOS DE VALIDACIÓN/CALIBRACIÓN

print("\n" + "="*65)
print("  ESTRATEGIA DE GESTIÓN Y PROCESOS DE MODELADO (ADICIONAL)")
print("="*65)
print("\n1. ESTRATEGIA Y TOMA DE DECISIONES:")
print("   - Situación Actual y Suficiencia: Actualmente, con 3 cajeros independientes,")
print("     el factor de utilización por cajero (Rho) es de aproximadamente 25.8%.")
print("     Esto indica que los cajeros se encuentran inactivos un 74.2% del tiempo.")
print("     Por lo tanto, la cantidad de 3 cajeros es completamente SUFICIENTE y no se")
print("     requiere aumentar este número.")
print("   - Criterio de Toma de Decisiones del Grupo:")
print("     * Criterio de Sobrecarga (Habilitación): Si el factor de utilización (Rho)")
print("       promedio del sistema supera el 75% o el tiempo en cola promedio (Wq)")
print("       es mayor a 3.0 minutos, se debe habilitar un cajero adicional temporal.")
print("     * Criterio de Subutilización (Optimización): Si la utilización promedio")
print("       es inferior al 35% (como ocurre actualmente), se puede operar con")
print("       solamente 2 cajeros en horarios valle (lo que subiría Rho a ~38.7%),")
print("       reduciendo costos operativos sin afectar significativamente la cola.")
print("     * Criterio de Calidad de Servicio: La espera promedio en cola no debe")
print("       superar el percentil 90 de 5.0 minutos.")
print("\n2. EXPLICACIÓN DE VERIFICACIÓN, CALIBRACIÓN Y VALIDACIÓN:")
print("   - Verificación: Es el proceso de asegurar que el software/código implementa")
print("     correctamente la lógica conceptual (no hay bugs matemáticos ni de flujo).")
print("     Se verificó controlando que los tiempos entre arribos acumulados se sumen")
print("     bien, que las transiciones en cola sean secuenciales y correctas, y que no")
print("     ocurran tiempos negativos ni solapamientos en los cajeros.")
print("   - Calibración: Es ajustar los parámetros estadísticos del modelo de acuerdo")
print("     con las mediciones del sistema real. Se calibró usando las medias ponderadas")
print("     de servicio (3.60 min) y llegada (4.65 min) y asignando la distribución")
print("     exponencial a cada tipo de usuario según su respectiva probabilidad empírica.")
print("   - Validación: Es determinar si el modelo simula con suficiente precisión la")
print("     realidad. Se validó comparando el tiempo total promedio en el sistema (W)")
print("     empírico obtenido de la simulación frente al resultado analítico de la")
print("     fórmula de colas M/M/1 teórica (W = 1 / (mu - lambda) = 4.85 min). La")
print("     última gráfica muestra cómo los tres cajeros convergen a este valor teórico.")
print("="*65)